package com.allme.back.user.infrastructure.archive;

import com.allme.back.global.crypto.AesGcmStringEncryptor;
import com.allme.back.user.application.port.WithdrawnUserArchivePort;
import jakarta.annotation.PostConstruct;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Component;

/**
 * 탈퇴 회원 보관소 어댑터 — 아카이브 DB(물리 분리)의 withdrawn_users 테이블에 저장한다.
 * 개인정보 컬럼은 본 DB와 같은 키(crypto.enc-key)로 암호화해 저장한다(평문 저장 금지).
 * user_id upsert라 같은 건의 재시도가 중복을 만들지 않는다.
 * 테이블은 자동 생성(CREATE TABLE IF NOT EXISTS) — 본 DB ddl-auto:update와 같은
 * 개발 전용 철학이며, 운영 전환 시 마이그레이션 도구로 교체한다.
 * 기동 시 아카이브 DB가 없어도 앱은 뜨고(경고만), 탈퇴 시점에만 실패한다 —
 * 포트원 미설정 시 U004처럼 "부가 인프라 부재가 전체 기동을 막지 않는" 기존 방침.
 */
@Slf4j
@Component
public class JdbcWithdrawnUserArchive implements WithdrawnUserArchivePort {

    private final JdbcClient jdbcClient;
    private final AesGcmStringEncryptor encryptor;

    public JdbcWithdrawnUserArchive(
        @Qualifier("archiveJdbcClient") JdbcClient jdbcClient,
        AesGcmStringEncryptor encryptor
    ) {
        this.jdbcClient = jdbcClient;
        this.encryptor = encryptor;
    }

    @PostConstruct
    void initSchema() {
        try {
            createTableIfNotExists();
        } catch (RuntimeException e) {
            log.warn("[Archive] 아카이브 DB 접속 실패 — 기동은 계속하고 탈퇴 시점에 재시도한다: {}",
                e.getMessage());
        }
    }

    void createTableIfNotExists() {
        jdbcClient.sql("""
            create table if not exists withdrawn_users (
                id bigint generated by default as identity primary key,
                user_id bigint not null unique,
                login_id varchar(20) not null,
                name varchar(512) not null,
                ci varchar(512) not null,
                ci_hash varchar(44) not null,
                di varchar(512),
                phone_number varchar(512),
                marketing_consent boolean not null,
                joined_at timestamp(6) not null,
                withdrawn_at timestamp(6) not null
            )
            """).update();
        jdbcClient.sql("""
            create table if not exists withdrawn_settlement_accounts (
                id bigint generated by default as identity primary key,
                user_id bigint not null unique,
                bank varchar(20) not null,
                account_number varchar(512) not null,
                account_holder varchar(512) not null,
                withdrawn_at timestamp(6) not null
            )
            """).update();
    }

    @Override
    public void archive(WithdrawnUser data) {
        // 기동 시 생성에 실패했을 수 있어 이관 직전에 재보장 (IF NOT EXISTS라 멱등·저비용)
        createTableIfNotExists();
        jdbcClient.sql("""
            insert into withdrawn_users
                (user_id, login_id, name, ci, ci_hash, di, phone_number,
                 marketing_consent, joined_at, withdrawn_at)
            values
                (:userId, :loginId, :name, :ci, :ciHash, :di, :phoneNumber,
                 :marketingConsent, :joinedAt, :withdrawnAt)
            on conflict (user_id) do update set
                login_id = excluded.login_id,
                name = excluded.name,
                ci = excluded.ci,
                ci_hash = excluded.ci_hash,
                di = excluded.di,
                phone_number = excluded.phone_number,
                marketing_consent = excluded.marketing_consent,
                joined_at = excluded.joined_at,
                withdrawn_at = excluded.withdrawn_at
            """)
            .param("userId", data.userId())
            .param("loginId", data.loginId())
            .param("name", encryptor.encrypt(data.name()))
            .param("ci", encryptor.encrypt(data.ci()))
            .param("ciHash", data.ciHash())
            .param("di", encryptor.encrypt(data.di()))
            .param("phoneNumber", encryptor.encrypt(data.phoneNumber()))
            .param("marketingConsent", data.marketingConsent())
            .param("joinedAt", data.joinedAt())
            .param("withdrawnAt", data.withdrawnAt())
            .update();
    }

    @Override
    public void archiveSettlementAccount(WithdrawnSettlementAccount data) {
        createTableIfNotExists();
        jdbcClient.sql("""
            insert into withdrawn_settlement_accounts
                (user_id, bank, account_number, account_holder, withdrawn_at)
            values
                (:userId, :bank, :accountNumber, :accountHolder, :withdrawnAt)
            on conflict (user_id) do update set
                bank = excluded.bank,
                account_number = excluded.account_number,
                account_holder = excluded.account_holder,
                withdrawn_at = excluded.withdrawn_at
            """)
            .param("userId", data.userId())
            .param("bank", data.bank())
            .param("accountNumber", encryptor.encrypt(data.accountNumber()))
            .param("accountHolder", encryptor.encrypt(data.accountHolder()))
            .param("withdrawnAt", data.withdrawnAt())
            .update();
    }

}
